Add update article for editors
dSHARP-CMU/archive_plugin pull request #10
Opened 2019-02-11 22:50 UTC by hachacha

This offers a button for updating an article on the `/x-journal/manage/archive/article/x/` page
![image](https://user-images.githubusercontent.com/1020384/52598892-2327f680-2e25-11e9-9c71-3fdc29f5c4fd.png)
Editors and authors of the article may update the article.

2019-02-12 14:20 UTC, mdlincoln commented on templates/archive_plugin/inject_request_edit_update.html
> +    <a class="success button" href="{% url 'update_type' article.pk %}">Update Article</a>
Silly question - is there a reason that the classes `button` and `success` are reversed here compared to the `request_update` button?

2019-02-12 14:27 UTC, hachacha commented on templates/archive_plugin/inject_request_edit_update.html
> +    <a class="success button" href="{% url 'update_type' article.pk %}">Update Article</a>
No, but I can swap them around just so it's consistent.
The order of classes as they appear in html does not matter but their individual order/position in the CSS file does have an influence so these don't really do anything.
And in this case their styles are actually being overruled by another line.
![image](https://user-images.githubusercontent.com/1020384/52641994-1ef0ed00-2ea8-11e9-932b-3e117ad30cdf.png)
I don't know why these styles were put in here but I was just trying to follow what was already in place.

2019-02-12 14:30 UTC, ajrbyers commented on templates/archive_plugin/inject_request_edit_update.html
> +    <a class="success button" href="{% url 'update_type' article.pk %}">Update Article</a>
I think these have been copied from another location, best to drop the `success` class as only `button` is need in a `title-area` link.

2019-02-12 15:25 UTC, mdlincoln requested changes

2019-02-12 15:25 UTC, mdlincoln commented on templates/archive_plugin/inject_request_edit_update.html
> +    <a class="button" href="{% url 'request_update' article.pk %}">Request update from registered owner</a>
Please rewrite the text on these links so that it's crystal clear that one will _send an email to the original author asking them to submit an update_, while the other will allow the editor to... do what? Submit something themselves?

This might be a case where we need [tooltips](https://foundation.zurb.com/sites/docs/v/5.5.3/components/tooltips.html)

2019-02-12 15:38 UTC, hachacha commented on templates/archive_plugin/inject_request_edit_update.html
> +    <a class="button" href="{% url 'request_update' article.pk %}">Request update from registered owner</a>
The other button allows the editor to create a new version of the article as per: https://github.com/dSHARP-CMU/cmesh-dev/issues/206#issuecomment-458225274

How about: `Request new version from article's author`
^tooltip: `Sends an email to the author requesting that they create a new version of this article.`
and: `submit new version as an editor`
^tooltip: `Begins the submission process for a new version of this article.`

tooltip seems to be available in the front-facing OLH theme in janeway core, I am not exactly sure if it will be available on the admin side on this particular page-- looking in to it.

2019-02-13 22:20 UTC, hachacha commented
@mdlincoln added tooltip with description of what buttons do. 
let me know if this satisfies the requested change ya

2019-02-13 22:40 UTC, mdlincoln approved these changes

2019-02-13 22:40 UTC, merged