Add search logic to archive_plugin
dSHARP-CMU/archive_plugin pull request #14
Opened 2019-03-18 16:39 UTC by hachacha

This **SHOULD** be a temporary fix until https://github.com/BirkbeckCTP/janeway/pull/918 can be merged and then will link up https://github.com/dSHARP-CMU/archive_plugin/blob/49d01433cbdc29adc02b7b9842c2d1751ad05083/logic.py#L80 somehow to capture the search results and display only the latest versions of articles.

2019-03-19 12:55 UTC, mdlincoln commented on logic.py
> +    final_articles = []
Would you be able to get the same effect with the database query:

```py
article_list.filter(updates__isnull=True)
```

(a shot in the dark here, I may be missing some odd behavior that this wouldn't check for)

2019-03-19 13:22 UTC, mdlincoln commented on logic.py
> +    final_articles = []
ohhh, you need to check if the "update" article has actually been published yes, correct? so it'd need to be more like

```py
article_list.exclude(Q(updates__isnull=False) | Q(updates__stage="Published"))
```

2019-03-19 15:29 UTC, hachacha commented on logic.py
> +    final_articles = []
It's possible to do it all in one query (or to send the article_list as a queryset for further querying) but I've found that it gets complicated with many-to-many fields in django. It sometimes can look messy whereas the `is_latest` function is pretty legible. It also was already in the `browse_entries` function so that can be abstracted out as well.

`updates__stage` doesn't exist because there could be multiple updates so you would have to get a list of those articles for each article via updates and check those stages.
if you think it'd be better to go with a single query, I could probably figure it out but this logic is easier to manage in my opinion.

2019-03-19 15:33 UTC, mdlincoln commented on logic.py
> +    final_articles = []
It may just be my R-based aversion to `for` loops coming through 😂 

>you would have to get a list of those articles for each article via updates and check those stages.

isn't that what the M2M query does though? If _any_ of the articles related via `updates` have `stage="Published"` then the article gets excluded?

2019-03-19 15:49 UTC, mdlincoln commented on logic.py
> +    final_articles = []
i.e. `updates__article__stage="Published"`

2019-03-19 16:38 UTC, hachacha commented on logic.py
> +    final_articles = []
`Article.objects.filter(journal=j, stage="Published").exclude(Q(updates__article__stage="Published"))` does the trick!
What I was thinking of doing to hook this back up to the search once it's merged in core was to use a templatetag for our TOC and search pages to further filter the results.
I'm looking in to it now to see whether or not a query will work within a templatetag, I think it might be discouraged.

2019-03-19 16:41 UTC, mdlincoln commented on logic.py
> +    final_articles = []
hrm, why a template tag? is it because the core search view already returns a fully rendered page, not a queryset you can further refine?

2019-03-19 16:42 UTC, mdlincoln commented on logic.py
> +    final_articles = []
also ps since that exclude now only has one query in it, I think you can remove the `Q()` surrounding it

2019-03-19 17:00 UTC, hachacha commented on logic.py
> +    final_articles = []
Yes it already renders a fully rendered page sending context to the search.html template. The logic is essientially exactly the same here.
I think that a templatetag feels least intrusive for the archive_plugin it's basically purely cosmetic on the templates. what do you think?

2019-03-19 17:02 UTC, ajrbyers commented on logic.py
> +    final_articles = []
I wonder if a hook in the core code to allow plugins to further filter search results may be a good solution?

2019-03-19 18:22 UTC, mdlincoln commented on logic.py
> +    final_articles = []
Is a hook a difficult thing to add in at this stage?

I believe the priority should be that anyone writing a template for the search results that use the archive_plugin shouldn't need to know anything about how they're delivered, so the less that this happens in the templates, and the more that happens in logic/views, the better.

2019-03-19 19:15 UTC, ajrbyers commented
I think it could be easily done. So at the end of the search view we can call something like:

articles = call_hook(‘search’, articles)

The archive plugin registers itself for the ‘search’ hook so it gets called and has the existing list of articles passed in, can filter them further and pass them back... 

Thoughts?

2019-03-19 19:35 UTC, mdlincoln commented
OK - what, if any, changes does this then mean for https://github.com/BirkbeckCTP/janeway/pull/918 ?

2019-03-19 19:55 UTC, hachacha commented
I think I see how this would work... 
This method should be registered in the `hook_registry` in `plugin_settings` and set up in the hooks.py file to capture the `article_list` from the request and then filter and send back to search?
This would also allow for a user to toggle on or off if they want the archive plugin to interact with search results and only show the latest published versions, right?
I haven't looked at the code revisions in the PR on janeway but I don't think that anything major would need to change in

2019-03-19 20:31 UTC, ajrbyers commented
> This would also allow for a user to toggle on or off if they want the archive plugin to interact with search results and only show the latest published versions, right?

Exactly!

2019-03-20 22:18 UTC, mdlincoln commented
Closes https://github.com/dSHARP-CMU/cmesh-dev/issues/303
Closes https://github.com/dSHARP-CMU/cmesh-dev/issues/139
Closes https://github.com/dSHARP-CMU/cmesh-dev/issues/152
Closes https://github.com/dSHARP-CMU/cmesh-dev/issues/153

2019-04-02 15:07 UTC, hachacha commented
I have created this so it's now a plugin setting and responds to a hook in the ethos_theme `filter_search` . it modifies the context containing the articles querystring to exclude older versions. you can toggle this feature on and off in the plugin settings manager.

The hook can be added to the search template here:
https://github.com/dSHARP-CMU/ethos_theme/tree/add_filter_search_hook

2019-04-02 15:31 UTC, mdlincoln requested changes

2019-04-02 15:31 UTC, mdlincoln commented on hooks.py
> +        excluded_articles_qs = articles_qs.exclude(updates__article__stage="Published")
Use `submission.models.STAGE_PUBLISHED` instead of `"Published"`

2019-04-02 15:39 UTC, hachacha commented on hooks.py
> +        excluded_articles_qs = articles_qs.exclude(updates__article__stage="Published")
Should this exclude logic be in views.py because that is normally where queryset management goes and that import is already in that file?

2019-04-02 15:45 UTC, mdlincoln commented on hooks.py
> +        excluded_articles_qs = articles_qs.exclude(updates__article__stage="Published")
Yes, I think you're right to try and put the queryset stuff in the same place.

2019-04-02 17:01 UTC, mdlincoln approved these changes

2019-04-02 17:01 UTC, mdlincoln commented
looks good to me! Ready to merge?

2019-04-02 17:24 UTC, merged